services:
  # === БАЗА ДАННЫХ (PostgreSQL) ===
  db:
    image: postgres:16
    container_name: zetom_db
    restart: always
    environment:
      # Твои реальные настройки
      POSTGRES_USER: zetom_user
      POSTGRES_DB: zetom
      POSTGRES_PASSWORD: AJNJDN14187LKKA983140JAJ5 # Пароль задаем здесь (можно поменять)
    volumes:
      # 1. СЮДА кладем твой файл init.sql, чтобы данные появились сами
      - ./db_setup/init.sql:/docker-entrypoint-initdb.d/init.sql
      # 2. Здесь данные будут храниться постоянно
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zetom_user -d zetom"]
      interval: 5s
      timeout: 5s
      retries: 5

  # === ТВОЙ САЙТ (Django) ===
  web:
    build: .
    container_name: zetom_app
    restart: on-failure
    ports:
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Настройки Django
      DJANGO_DEBUG: "true"
      DJANGO_ALLOWED_HOSTS: "*"
      CSRF_TRUSTED_ORIGINS: "https://shalyn42k.pl"
      # Строка подключения: postgres://ПОЛЬЗОВАТЕЛЬ:ПАРОЛЬ@ХОСТ:ПОРТ/БАЗА
      DATABASE_URL: postgres://zetom_user:AJNJDN14187LKKA983140JAJ5@db:5432/zetom
    volumes:
      - ./:/app

volumes:
  postgres_data:
