services:
  - type: web
    name: zetom
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn zetom_project.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: "${RENDER_EXTERNAL_HOSTNAME}"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DATABASE_URL
        fromDatabase:
          name: zetom-db
          property: connectionString
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://${RENDER_EXTERNAL_HOSTNAME}"
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: DEFAULT_LANGUAGE
        value: pl
    autoDeploy: true
    healthCheckPath: /
databases:
  - name: zetom-db
    plan: free
    ipAllowList: []
