# Generated by Django 5.2.7 on 2025-10-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_contactmessage_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="final_changes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="final_response",
            field=models.TextField(blank=True),
        ),
    ]
