# Generated by Django 5.2.7 on 2025-10-22 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_contactmessage_final_changes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessageRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "editor",
                    models.CharField(
                        choices=[("user", "user"), ("admin", "admin")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("previous_data", models.JSONField(default=dict)),
                ("new_data", models.JSONField(default=dict)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="contact.contactmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
