# Generated by Django 5.2.7 on 2025-10-27 12:20

import django.db.models.deletion
# === FILE SUMMARY ===
# Purpose: Add access token fields and access control flags to ContactMessage.
# Responsible for: Introducing access_token_hash, access_enabled flag, and index adjustments.
# Connected to: ContactMessage methods handling token-based access.
# Important classes/functions: Migration
# Notes: Supports user self-service access to requests.
# =====================================
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_contactmessage_final_changes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="access_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="access_token_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name="ContactAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/%Y/%m/%d")),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="contact.contactmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
