# Generated by Django 5.2.7 on 2025-10-27 11:46

import hashlib
import math
import secrets

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import contact.models


def _token_length():
    length = getattr(settings, "REQUEST_TOKEN_LENGTH", 40)
    return max(32, min(48, int(length)))


def _generate_token(existing):
    target = _token_length()
    for _ in range(20):
        nbytes = max(24, math.ceil(target * 3 / 4))
        token = secrets.token_urlsafe(nbytes)
        if len(token) > target:
            token = token[:target]
        while len(token) < target:
            token += secrets.token_urlsafe(4)
            if len(token) > target:
                token = token[:target]
        if token not in existing:
            return token
    raise RuntimeError("Unable to generate unique access token")


def populate_tokens(apps, schema_editor):
    Request = apps.get_model("contact", "Request")
    existing = set(Request.objects.exclude(access_token__isnull=True).values_list("access_token", flat=True))
    for request in Request.objects.all():
        token = _generate_token(existing)
        existing.add(token)
        request.access_token = token
        request.access_token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
        if request.updated_at is None:
            request.updated_at = django.utils.timezone.now()
        if request.access_enabled is None:
            request.access_enabled = True
        request.save(update_fields=["access_token", "access_token_hash", "updated_at", "access_enabled"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_contactmessage_final_changes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        max_length=100,
                        unique=True,
                        validators=[django.core.validators.validate_slug],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.RenameModel(old_name="ContactMessage", new_name="Request"),
        migrations.AlterModelOptions(name="request", options={"ordering": ["-created_at"]}),
        migrations.AlterModelTable(name="request", table="contact_contactmessage"),
        migrations.AddField(
            model_name="request",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="request",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="contact.department",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="access_token",
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="request",
            name="access_token_hash",
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="access_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Administrator"), ("employee", "Employee")],
                        max_length=16,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_members",
                        to="contact.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "staff profile",
                "verbose_name_plural": "staff profiles",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("comment", "Comment"),
                            ("status_change", "Status change"),
                            ("assignment", "Assignment"),
                            ("file_upload", "File upload"),
                            ("system", "System"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="contact.request",
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=contact.models.attachment_upload_to)),
                ("original_name", models.CharField(max_length=255)),
                ("size", models.BigIntegerField()),
                ("content_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="contact.request",
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.RunPython(populate_tokens, noop_reverse),
        migrations.AlterField(
            model_name="request",
            name="access_token",
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="access_token_hash",
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
    ]
