# Generated by Django 5.2.7 on 2025-10-29 12:30

# === FILE SUMMARY ===
# Purpose: Introduce expiration timestamp and access token index to ContactMessage.
# Responsible for: Adding access_token_expires_at field and altering database index for tokens.
# Connected to: ContactMessage access control and token validation logic.
# Important classes/functions: Migration
# Notes: Supports time-bound access tokens for user edits.
# =====================================
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0005_contactmessage_access_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="access_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="company",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
