# Generated by Django 5.2.7 on 2025-10-29 15:19

import django.db.models.deletion
from django.db import migrations, models


def combine_names(apps, schema_editor):
    ContactMessage = apps.get_model('contact', 'ContactMessage')
    for message in ContactMessage.objects.all():
        first = getattr(message, 'first_name', '') or ''
        last = getattr(message, 'last_name', '') or ''
        parts = [part.strip() for part in (first, last) if part.strip()]
        if parts:
            full_name = ' '.join(parts)
        else:
            fallback = getattr(message, 'email', '') or 'Unknown'
            full_name = fallback
        message.full_name = full_name.strip()
        message.save(update_fields=['full_name'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0006_contactmessage_access_token_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=150),
            preserve_default=False,
        ),
        migrations.RunPython(combine_names, noop_reverse),
        migrations.RemoveField(
            model_name='contactmessage',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='last_name',
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('status_change', 'status_change'), ('delete', 'delete'), ('restore', 'restore'), ('purge', 'purge'), ('email', 'email'), ('rollback', 'rollback')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to='contact.contactmessage')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ClientChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('full_name', 'full_name'), ('phone', 'phone'), ('email', 'email'), ('company', 'company'), ('company_name', 'company_name'), ('message', 'message')], max_length=32)),
                ('previous_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_reverted', models.BooleanField(db_index=True, default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_logs', to='contact.contactmessage')),
            ],
            options={'ordering': ['-changed_at', '-id']},
        ),
    ]
