# Generated by Django 5.2.8 on 2025-11-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0007_rename_name_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("token_hash", models.CharField(max_length=128)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("level1", "Level 1"),
                            ("level2", "Level 2"),
                            ("level3", "Level 3"),
                        ],
                        default="level3",
                        max_length=16,
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, default="all", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["email"],
            },
        ),
    ]
