# === FILE SUMMARY ===
# Purpose: Create the AdminUser model for managing admin access levels.
# Responsible for: Defining fields for email, password hash, access level, and timestamps.
# Connected to: AdminUser model in application code.
# Important classes/functions: Migration
# Notes: Generated migration introducing admin user support.
# =====================================
# Generated by Django 5.2.8 on 2025-11-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0007_rename_name_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=128)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("level1", "Admin"),
                            ("level2", "Department"),
                            ("level3", "Tester"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
