# Generated by Django 5.2.8 on 2025-11-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0012_department_remove_adminuser_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="last_password_reset_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
