# Generated by Django 5.2.9 on 2025-12-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0014_update_departments_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="permissions_override",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
