# Generated by Django 5.2.10 on 2026-01-24 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0016_contactmessage_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminactivitylog",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_logs",
                to="contact.contactmessage",
            ),
        ),
    ]
